import { Rubik } from 'next/font/google'
import './globals.css'

const rubik = Rubik({ 
  subsets: ['latin'],
   weight : ['300','400','500','600','700','800'],
  variable : '--font-rubik'
 })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
     

      </head>
      <body className={rubik.variable}>{children}</body>

    </html>
  )
}
